export const loaderActions = {
  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER',
  APP_ERROR: 'APP_ERROR',
};

export const LOGOUT = 'LOGOUT';

export const existingUserActions = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  VALIDATE_CUSTOMER_REQUEST: 'VALIDATE_CUSTOMER_REQUEST',
  VALIDATE_CUSTOMER_FAILURE: 'VALIDATE_CUSTOMER_FAILURE',
  VALIDATE_CUSTOMER_SUCCESS: 'VALIDATE_CUSTOMER_SUCCESS',
  APP_UPDATE_INFO: 'APP_UPDATE_INFO',
};

export const UPLOADFILETYPES = {
  SET_UPLOAD_FILE: 'SET_UPLOAD_FILE',
  SET_UPLOAD_PROGRESS: 'SET_UPLOAD_PROGRESS',
  SUCCESS_UPLOAD_FILE: 'SUCCESS_UPLOAD_FILE',
  FAILURE_UPLOAD_FILE: 'FAILURE_UPLOAD_FILE',
  RESET_UPLOAD: 'RESET_UPLOAD',
};
